#!/bin/bash
# Check for specific interface if desired
#[ "$PPP_IFACE" != "ppp0" ] || exit 0


rm -f /etc/dnsmasq.conf
rm -f /var/lib/misc/dnsmasq.leases
/usr/sbin/ip -4 addr flush enp88s0
/usr/sbin/ip addr add 172.17.0.1/24 dev enp88s0
/usr/bin/systemctl stop dnsmasq